project:
  type: book
  output-dir: docs

book:
  title: ""
  subtitle: "Kevin's Collection of PSPE Methodology Resources"
  search: true
  sidebar:
    collapse-level: 1
    pinned: true
    title: ""
    style: floating
    border: true
    background: "#f8f9fa"
    foreground: "#36026b"
    logo: lse.png
  chapters:
    - index.qmd
    - part: frameworks.qmd
      chapters:
        - correlation.qmd
        - randomisation.qmd
    - "---"
    - part: did.qmd
      chapters:
        - did.qmd
    - part: rdd.qmd
      chapters:
        - fuzzy.qmd
    - part: soo.qmd
      chapters:
        - regress.qmd
        - distance.qmd
        - pscore.qmd
        - genetic.qmd
        - weighting.qmd
    - part: "Instrumental Variables"
    - "---"
    - part: "Regression Models"
    - part: "Latent Variable Models"
    - "---"
    - part: "Further Statistical Models"
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    fontsize: 12.5pt
    mainfont: helvetica
    fontcolor: "#3b4b57"
    linkcolor: "#0969da"
    css: styles.css
    toc: true
    toc-depth: 0
    tbl-cap-location: bottom
    reference-location: section
    grid:
      sidebar-width: 270px
      body-width: 720px
      margin-width: 50px
      gutter-width: 1.5em
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
    include-after-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

editor: visual

