# Welcome {.unnumbered}

This is a collection of resources and notes for political science and political economy methodology that I have collected throughout my postgraduate degree at the London School of Economics. I hope this resource can be useful to both myself and others!

The resources in this collection include:

-   Causal inference, including details (and modern advancements) in difference-in-differences, regression discontinuity, and selection on observables.
-   Some general content on statistical models.

The sidebar/menu contains parts. Each part contains an overview, and several follow-up pages regarding specific estimators/topics.

<br />

Notation note: As with most causal inference notation, I will use capital letters to reference variables (such as treatment, outcome).

I will use vectors/matrices for shortening regression equations. Because I am using capital letters to refer to variables, some vectors might be capitalised - which does not follow normal mathematical notation. Example: $\b X_i$ might be a vector of confounder values for unit $i$.
