# How Matching Works {.unnumbered}

<br />

Mia is in our study and receives the treatment. Mia's individual causal effect is:

$$
\tau_{\text{Mia}} = \textcolor{purple}{Y^{(1)}_\text{Mia}} - \textcolor{red}{Y^{(0)}_\text{Mia}}
$$

::: aside
The counterfactual in red is unobserved.
:::

Since Mia receives the treatment in real life, we cannot observe the counterfactual where Mia does not get the treatment. However, we can **estimate** Mia's counterfactual by finding someone else in our study, who did not receive the treatment, but is also really **similar** to Mia in all other ways.

Let's say Ava is really similar to Mia. Ava also happens to have not received the treatment. We can approximate Mia's counterfactual using Ava's observed outcome:

$$
\textcolor{red}{Y^{(0)}_\text{Mia}} \approx \textcolor{purple}{Y^{(0)}_\text{Ava}}
$$

Having approximated Mia's counterfactual, we can now estimate Mia's causal effect, as both quantities are observed:

$$
\widehat\tau_{\text{Mia}} = \textcolor{purple}{Y^{(1)}_\text{Mia}} - \textcolor{purple}{Y^{(0)}_\text{Ava}} = Y_\text{Mia} - Y_\text{Ava}
$$

We can do the matching for every single person in the treatment group, then average all of these individual causal effects to get an estimate of the **ATT**.

By matching individuals with the **same/very similar confounder values**, we eliminate pre-existing differences, since our matched pairs will all be similar to each other. Thus, selection bias will not be a concern.

<br />

For matching to work, we must meet the following three assumptions:

+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| Assumption                                              | Description                                                                                                                                               | How to Check                                                                                                                          |
+:========================================================+:==========================================================================================================================================================+:======================================================================================================================================+
| [Conditional Ignorability]{.mark}                       | This means that when we match, we must account for all possible confounders.                                                                              | We can conduct balance checks.                                                                                                        |
+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| [Common Support]{.mark}                                 | This means no one can have a 100% chance of being in treatment or control. They always have a chance to be in either, no matter their confounding values. | Hard to check. One way to sort of check is to see if you have a treated and untreated unit for every confounder value in your sample. |
+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| [Stable Unit Treatment Value Assumption (SUTVA)]{.mark} | This means that if Ava is treated, that does not affect Mia's outcome (and for any other 2 individuals).                                                  | We have to use our own theoretical reasoning.                                                                                         |
+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+

: Ensure all of these assumptions are met if you are using matching {#tbl-matching tbl-colwidths="\[22,43,35\]" .bordered}

<br />

There are three estimators to implement matching. These are essentially different ways to calculate which units are "closest" to each other for matching.

+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Estimator                                        | Kevin's Rating                                                                                                                          | When to Use                                                                                    |
+==================================================+=========================================================================================================================================+================================================================================================+
| [[Distance Matching](distance.qmd)]{.mark}       | <div>                                                                                                                                   | When genetic matching is not possible, and we have less than 5 confounders and a small sample. |
|                                                  |                                                                                                                                         |                                                                                                |
|                                                  | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i> |                                                                                                |
|                                                  |                                                                                                                                         |                                                                                                |
|                                                  | </div>                                                                                                                                  |                                                                                                |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| [[Propensity Score Matching](pscore.qmd)]{.mark} | <div>                                                                                                                                   | When genetic matching is not possible, and we have a large sample.                             |
|                                                  |                                                                                                                                         |                                                                                                |
|                                                  | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i> |                                                                                                |
|                                                  |                                                                                                                                         |                                                                                                |
|                                                  | </div>                                                                                                                                  |                                                                                                |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| [[Genetic Matching](genetic.qmd)]{.mark}         | <div>                                                                                                                                   | Whenever possible. Can require a good computer and take long for large data sets.              |
|                                                  |                                                                                                                                         |                                                                                                |
|                                                  | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i> |                                                                                                |
|                                                  |                                                                                                                                         |                                                                                                |
|                                                  | </div>                                                                                                                                  |                                                                                                |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[27,33,40\]" .bordered}

Use the sidebar or links in the table to access each estimator's page.
