# Selection on Observables {.unnumbered}

::: small
This is an overview of selection on observables. For estimators and R-code, use the sidebar.
:::

Our issue in causal inference is that a confounder is causing pre-existing differences:

::: center-graph
```{dot}
//| fig-width: 4
//| fig-height: 1.1
digraph example2 {
  // Nodes
  D [shape=box, pos = "0,0!", label="Receiving Scholarship"]
  X [shape=box, pos = "2,0!", label="Intellegence (Confounder)"]
  Y [shape=box, pos = "1,-1!", label="University Grades"]

  // Edges
  {rank=same; D -> Y [label="Causal Effect"]}
  X -> D
  X -> Y [dir=both]
  
  graph [nodesep=0.5, ranksep=0.5]

}
```
:::

By definition, as the confounder **changes**, your likelihood of getting treatment changes. As the confounder **changes**, the outcome value will also change.

These issues occur when the confounder **changes** in value. So what if we hold the confounders constant? Let's assume that intellegence has two values: smart and dumb. Let us calculate the treatment effect within each level of intellegence:

$$
\tau_\text{smart} = \purple{\mean Y_\text{smart}^{(1)}} - \purple{\mean Y_\text{smart}^{(0)}}
, \quad \tau_\text{dumb} = \purple{\mean Y_\text{dumb}^{(1)}} - \purple{\mean Y_\text{dumb}^{(0)}}
$$

::: small
Obviously, most confounders will not have only 2 values. But the same intuition applies - for each value of confounders, we split all individuals into groups, and calculate the average treatment effect within each group.
:::

The confounder is constant here, so no selection bias. Thus, within each category, correlation is equal to causation. Our overall causal effect will be a weighted average of the categories:

$$
\tau = \tau_\text{smart} Pr(\text{smart})  \ + \ \tau_\text{dumb} Pr(\text{dumb})
$$

::: small
The weights of this weighted average are the probability/frequency of that value of the confounder. A more formal proof is provided in the [appendix].
:::

For selection on observables to work, we need to meet 3 assumptions:

+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Assumption]{.smallcaps}                                | [Description]{.smallcaps}                                                                                                                                 |
+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Conditional Ignorability]{.mark}                       | This means that we must account for **all** possible confounders (cannot miss a single one).                                                              |
+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Common Support]{.mark}                                 | This means no one can have a 100% chance of being in treatment or control. They always have a chance to be in either, no matter their confounding values. |
+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Stable Unit Treatment Value Assumption (SUTVA)]{.mark} | This means that if Ava is treated, that does not affect Mia's outcome (and for any other 2 individuals).                                                  |
+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[35,65\]" .bordered}

::: small
A more formal definition of these assumptions is provided in the [appendix].
:::

We have a wide choice of estimators that we can use.

+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| [Estimator]{.smallcaps}                        | [Kevin's Rating]{.smallcaps}                                                                                                            |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| [Fully Interacted Estimator](regress.qmd)      | <div>                                                                                                                                   |
|                                                |                                                                                                                                         |
|                                                | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i> |
|                                                |                                                                                                                                         |
|                                                | </div>                                                                                                                                  |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| [Distance Matching](distance.qmd)              | <div>                                                                                                                                   |
|                                                |                                                                                                                                         |
|                                                | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i> |
|                                                |                                                                                                                                         |
|                                                | </div>                                                                                                                                  |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| [Propensity Score Matching](pscore.qmd)        | <div>                                                                                                                                   |
|                                                |                                                                                                                                         |
|                                                | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i> |
|                                                |                                                                                                                                         |
|                                                | </div>                                                                                                                                  |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| [Genetic Matching](genetic.qmd)                | <div>                                                                                                                                   |
|                                                |                                                                                                                                         |
|                                                | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i> |
|                                                |                                                                                                                                         |
|                                                | </div>                                                                                                                                  |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| [Inverse Probability Weighting](weighting.qmd) | <div>                                                                                                                                   |
|                                                |                                                                                                                                         |
|                                                | <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i> |
|                                                |                                                                                                                                         |
|                                                | </div>                                                                                                                                  |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[63,37\]" .bordered}

::: small
Important: You should not always go for the higher rated estimator. Each estimator has its strengths/weaknesses, which the links for each page explain in more detail.
:::

Use the sidebar or links in the table to access each estimator's page.

<br />

#### Appendix

::: {.callout-note collapse="true"}
## Appendix A: Formal Definition of Assumptions

**Conditional ignorability** is the assumption that among units $i$ with identical confounder values $\b X_i = \b x$, treatment $D_i$ is as-if randomly assigned. This also means potential outcomes are independent from treatment given $\b X_i$.

$$
(\C, \T) \ind D_t \ | \ \b X_i = \b x
$$

This assumption implies the following:

$$
\begin{align}
& \E(\C | D_i = 1, \b X_i = \b x) = \E(\C | D_i = 0, \b X_i = \b x) = \E(\C | \b X_i = \b x) \\
& \E(\T | D_i = 1, \b X_i = \b x) = \E(\T | D_i = 0, \b X_i = \b x) = \E(\T | \b X_i = \b x) 
\end{align}
$$

**Common Support** implies that for any unit $i$ with any value of confounders, they have a non-zero probability they can be assigned to both treatment and control.

$$
0 < Pr(D_i = 1 | \b X_i = \b x) < 1
$$

For all possible confounder values $\b x$.
:::

::: {.callout-note collapse="true"}
## Appendix B: Identification Proof of ATE

Be sure to see appendix A before starting this.

Let us first find the conditional ATE, conditional on a specific confounder value $\b x$:

$$
\begin{align}
\tau(\b x) & = \E(\T - \C) | \b X_i = \b x) \\
& = \E(\T | \b X_i = \b x) - \E(\C | \b X_i = \b x)
\end{align}
$$

Now, from the properties implied by conditional ignorability from appendix A, we get:

$$
\begin{align}
\tau(\b x) & = \E(\T | D_i = 1, \b X_i = \b x) - \E(\C | D_i = 0, \b X_i = \b x) \\
& = \E(Y_i | D_i = 1, \b X_i = \b x) - \E(Y_i |D_i = 0, \b X_i = \b x
\end{align}
$$

Now, we can see under conditional ignorability, the conditional ATE is identifiable as all quantities are observed.

Now, let us consider the definition of the ATE - which is a weighted average of all conditional ATE's:

$$
\tau_{ATE} = \int \tau(\b x) \ d Pr(\b x)
$$

We already know we can identify $\tau(\b x)$. So, that means we have all we need to identify the ATE.
:::

::: {.callout-note collapse="true"}
## Appendix C: Identification Proof of ATT

Be sure to see appendix A before starting this.

Let us first find the conditional ATE, conditional on a specific confounder value $\b x$:

$$
\begin{align}
\tau(\b x) & = \E(\T - \C) | \b X_i = \b x) \\
& = \E(\T | \b X_i = \b x) - \E(\C | \b X_i = \b x)
\end{align}
$$

Now, from the properties implied by conditional ignorability from appendix A, we get:

$$
\begin{align}
\tau(\b x) & = \E(\T | D_i = 1, \b X_i = \b x) - \E(\C | D_i = 0, \b X_i = \b x) \\
& = \E(Y_i | D_i = 1, \b X_i = \b x) - \E(Y_i |D_i = 0, \b X_i = \b x
\end{align}
$$

Now, we can see under conditional ignorability, the conditional ATE is identifiable as all quantities are observed.

Now, let us consider the definition of the ATT - which is a weighted average of all conditional ATE's but only for treated individuals.

$$
\tau_{ATE} = \int \tau(\b x) \ d Pr(\b x| D_i = 1)
$$

We already know we can identify $\tau(\b x)$. So, that means we have all we need to identify the ATE.
:::
